easy_admin:
  site_name: 'Birthday Notifier'
  user:
    display_name: false
    display_avatar: false
  entities:
    Birthday:
      class: App\Entity\Birthday
      list:
        fields:
          - 'id'
          - 'name'
          - { property: 'date', type: 'date' }
      form:
        fields:
          - { property: 'date', type: 'birthday' }
          - 'name'
    Email:
      label: Email for notification
      class: App\Entity\Email
      form:
        fields:
          - { property: 'email', type: 'email' }
