easy_admin:
  site_name: 'Birthday Notifier'
  user:
    display_name: false
    display_avatar: false
  entities:
    Birthday:
      class: App\Entity\Birthday
      list:
        fields: ['id', 'name', 'date']
